name: Basic test workflow

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
#          - macos-latest
         - ubuntu-latest
#          - windows-latest
        ocaml-version:
          - 4.14.0
#          - 4.10.1
#          - 4.09.1
#          - 4.08.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Try to restore opam cache
        if: runner.os != 'Windows'
        id: opam-cache
        uses: actions/cache@v2
        with:
          path: "~/.opam"
          key: ${{ matrix.os }}-${{ matrix.ocaml-version }}  

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Install system dependencies
        run: |
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y bubblewrap darcs g++-multilib gcc-multilib mercurial musl-tools

          wget https://darcs.haskell.org/darcs-2.14.3.tar.gz
          tar -xvzf darcs-2.14.3.tar.gz
          cd darcs-2.14.3
          ./configure
          make
          sudo make install
          cd ..
          rm -rf darcs-2.14.3 darcs-2.14.3.tar.gz

      - run: opam install dune
      - name: Build project
        run: eval $(opam env) && make build
      - name: Run demo
        run: eval $(opam env) && make demo

